# Generated by Django 3.2 on 2022-06-30 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wearedevelopersapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Blog',
            new_name='Blogs',
        ),
    ]
