# Generated by Django 3.2 on 2022-07-04 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wearedevelopersapp', '0005_rename_trial_demofunction'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DemoFunction',
            new_name='Demo',
        ),
    ]
