# Generated by Django 3.2 on 2022-07-04 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wearedevelopersapp', '0006_rename_demofunction_demo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demo',
            name='image',
        ),
    ]
